name: Deploy to Google Apps Script

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install clasp
      run: npm install -g @google/clasp
    
    - name: Setup clasp credentials
      run: |
        echo '${{ secrets.CLASP_TOKEN }}' > ~/.clasprc.json
      env:
        CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}
    
    - name: Deploy to Apps Script
      run: |
        clasp push
      env:
        CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}
    
    - name: Deployment Status
      run: |
        echo "✅ Deployment to Google Apps Script completed successfully!"
        echo "🎉 Meeting Notes Agent add-on has been updated!"
